In [50]:
import numpy as np
import torch

In [10]:
emb_size = 4
rawf_size = 10

l = [emb_size + rawf_size]

l + [100]*2

[14, 100, 100]

In [11]:
l = [emb_size + rawf_size]
for layer in range(1,3):
    l.append(100)

l

[14, 100, 100]

In [ ]:
ll = torch.nn.ModuleList()

ll.append(torch.nn.LSTMCell(10,10))

ModuleList(
  (0): LSTMCell(10, 10)
)

In [1]:
cls = torch.nn.LSTMCell
cls()

NameError: name 'torch' is not defined

In [7]:
hidden_states = []
for _ in range(2):
    hidden_states.append(torch.zeros(5, 2*4))
hidden_states

[tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]])]

In [ ]:
[10 + 10] + [10]

[20]

In [4]:
import numpy as np

def sig(z):
    return 1.0/(1 + np.exp(-(z)))


z = np.array([0.6, 1.2, 1000.6])

sig(z)

array([0.64565631, 0.76852478, 1.        ])

In [2]:
torch.zeros(8, 2*4)

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [118]:
np.sqrt(1/50)

np.float64(0.1414213562373095)

In [ ]:
weights = torch.nn.Parameter(torch.normal(0.0, 0.05, size=(2,3)))

weights

Parameter containing:
tensor([[-0.0599,  0.0084, -0.0470],
        [-0.0566, -0.0188, -0.0954]], requires_grad=True)

: 

In [99]:
torch.var(weights, dim=1)

tensor([1.0142, 1.3352], grad_fn=<VarBackward0>)

In [120]:
torch.ones(1, 4)*2

tensor([[2., 2., 2., 2.]])

In [70]:
ten = torch.tensor([[1,2,3,4],[1,2,3,4]])
ten = torch.unsqueeze(ten, dim=2)
ten.shape

torch.Size([2, 4, 1])

In [72]:
ten_squeezed = torch.squeeze(ten)
ten_squeezed.shape

torch.Size([2, 4])

In [100]:
ten = torch.tensor([[1,2,3,4],[1,2,3,4]], dtype=float)
ten

tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.]], dtype=torch.float64)

In [101]:
m = torch.nn.Softmax(dim=1)
m(ten)

tensor([[0.0321, 0.0871, 0.2369, 0.6439],
        [0.0321, 0.0871, 0.2369, 0.6439]], dtype=torch.float64)

In [103]:
torch.softmax(ten, dim=1)

tensor([[0.0321, 0.0871, 0.2369, 0.6439],
        [0.0321, 0.0871, 0.2369, 0.6439]], dtype=torch.float64)

In [136]:
t = torch.ones([1,2,3,4])
t

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])

In [137]:
torch.flatten(t, start_dim=1, end_dim=2)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])